/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated.messages'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated.org'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated.people'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated.runs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated.status'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated.people.index'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated.people.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPeopleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/org': typeof AuthenticatedOrgRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/runs': typeof AuthenticatedRunsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/org': typeof AuthenticatedOrgRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/runs': typeof AuthenticatedRunsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/integrations'
    | '/messages'
    | '/org'
    | '/people'
    | '/runs'
    | '/settings'
    | '/status'
    | '/people/$id'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/integrations'
    | '/messages'
    | '/org'
    | '/runs'
    | '/settings'
    | '/status'
    | '/'
    | '/people/$id'
    | '/people'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/integrations'
    | '/_authenticated/messages'
    | '/_authenticated/org'
    | '/_authenticated/people'
    | '/_authenticated/runs'
    | '/_authenticated/settings'
    | '/_authenticated/status'
    | '/_authenticated/'
    | '/_authenticated/people/$id'
    | '/_authenticated/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
  }
}

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedRunsRoute: AuthenticatedRunsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
